name: Run tests and build documentation

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make venv
    - name: Perform tests
      run: make test



  badges:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Compute badges
      run: |
        make venv
        make test
        make badges
    - name: Update badges
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          # Working directory clean
          echo "nothing to commit"
        else
          # set user info
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
        
          # commit and push
          git add .
          git commit -m "CI: Update badges"
          git push
        fi
    - uses: actions/upload-artifact@v3
      with:
        path: _pages



  docs:
    runs-on: ubuntu-latest
    needs: [badges]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          cd docs && make clean html
          cd .. && sphinx-build docs _pages_build
      - uses: actions/download-artifact@v3
        with:
          path: _pages
      - name: Move _pages folder to _pages_build to push to gh_pages branch
        run: mv _pages/artifact/* _pages_build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _pages_build/
          force_orphan: true